// <auto-generated />
using ASPNetExapp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPNetExapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322200323_InitialCreateWithData")]
    partial class InitialCreateWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASPNetExapp.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComputerInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComputerInfo = "Asus Vivobook",
                            Department = "Backend",
                            LastName = "Ivanich",
                            RoomNumber = 15
                        },
                        new
                        {
                            Id = 2,
                            ComputerInfo = "Asus Pro Vivobook",
                            Department = "Frontend",
                            LastName = "Fofich",
                            RoomNumber = 15
                        },
                        new
                        {
                            Id = 3,
                            ComputerInfo = "Macbook",
                            Department = "UI",
                            LastName = "Bazzich",
                            RoomNumber = 15
                        },
                        new
                        {
                            Id = 4,
                            ComputerInfo = "Asus Vivobook",
                            Department = "UX",
                            LastName = "Gedich",
                            RoomNumber = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
